# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fec4208738940090856e4199149075923f7a04f1ad96f3bf91ebd28b01d5fcc095c15359cd5c59d4fed42a6343e3f1ca32dbcca91a73c1f209f88bbb3deaebab

test:
  secret_key_base: 5659be7a76c0fd9542ebd7ea9758055f6162d6985b98d8ef3761122353e0199fa9971d63ef6811005500264a8dab7387909d9f4dba4da94b0c966e25488a3b4f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
